#!/bin/bash

# Halt commands if an error occured
set -e

# Disable default compositor
Configfile="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
[ -e $Configfile ] || {
    mkdir -p $(dirname $Configfile)
    echo '<?xml version=\"1.0\" encoding=\"UTF-8\"?>
        <channel name=\"xfwm4\" version=\"1.0\">

        <property name=\"general\" type=\"empty\">
            <property name=\"use_compositing\" type=\"bool\" value=\"false\"/>
        </property>
    </channel>
    ' >$Configfile
}

exec startxfce4
